CREATE TABLE m_admins (
	id 				INT PRIMARY KEY AUTO_INCREMENT,
	username 		VARCHAR(191) UNIQUE NOT NULL,
	password 		VARCHAR(191) NOT NULL,
	last_login 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	status 			TINYINT(1) DEFAULT 1,
	created_at 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at 		TIMESTAMP NULL DEFAULT NULL,
	deleted_at 		TIMESTAMP NULL DEFAULT NULL,
	created_by		VARCHAR(191) DEFAULT NULL,
	updated_by		VARCHAR(191) DEFAULT NULL,
	deleted_by		VARCHAR(191) DEFAULT NULL
);

CREATE TABLE donation (
	id 				INT PRIMARY KEY AUTO_INCREMENT,
	nrp 			CHAR(9) NOT NULL,
	name			VARCHAR(191) NOT NULL,
	nominal 		BIGINT NOT NULL,
	time_stamp		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	status 			TINYINT(1) DEFAULT 1,
	created_at 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at 		TIMESTAMP NULL DEFAULT NULL,
	deleted_at 		TIMESTAMP NULL DEFAULT NULL,
	created_by		VARCHAR(191) DEFAULT NULL,
	updated_by		VARCHAR(191) DEFAULT NULL,
	deleted_by		VARCHAR(191) DEFAULT NULL
);

CREATE TABLE m_tipe_lomba (
	id				INT PRIMARY KEY AUTO_INCREMENT,
	name			VARCHAR(191) NOT NULL,

	status 			TINYINT(1) DEFAULT 1,
	created_at 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at 		TIMESTAMP NULL DEFAULT NULL,
	deleted_at 		TIMESTAMP NULL DEFAULT NULL,
	created_by		VARCHAR(191) DEFAULT NULL,
	updated_by		VARCHAR(191) DEFAULT NULL,
	deleted_by		VARCHAR(191) DEFAULT NULL
);

CREATE TABLE m_peserta_lomba (
	id 				INT PRIMARY KEY AUTO_INCREMENT,
	nrp 			CHAR(9) NOT NULL,
	name			VARCHAR(191) NOT NULL,
	tipe_lomba_id	INT NOT NULL,

	status 			TINYINT(1) DEFAULT 1,
	created_at 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at 		TIMESTAMP NULL DEFAULT NULL,
	deleted_at 		TIMESTAMP NULL DEFAULT NULL,
	created_by		VARCHAR(191) DEFAULT NULL,
	updated_by		VARCHAR(191) DEFAULT NULL,
	deleted_by		VARCHAR(191) DEFAULT NULL,

	CONSTRAINT fk_lomba_peserta_lomba 
		FOREIGN KEY (tipe_lomba_id) REFERENCES tipe_lomba(id)
);

CREATE TABLE m_tipe_user (
	id				INT PRIMARY KEY AUTO_INCREMENT,
	name			VARCHAR(191) NOT NULL,

	status 			TINYINT(1) DEFAULT 1,
	created_at 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at 		TIMESTAMP NULL DEFAULT NULL,
	deleted_at 		TIMESTAMP NULL DEFAULT NULL,
	created_by		VARCHAR(191) DEFAULT NULL,
	updated_by		VARCHAR(191) DEFAULT NULL,
	deleted_by		VARCHAR(191) DEFAULT NULL
);

CREATE TABLE m_lk (
	id 				INT PRIMARY KEY AUTO_INCREMENT,
	name 			VARCHAR(191),
	total_donasi	BIGINT DEFAULT 0,

	status 			TINYINT(1) DEFAULT 1,
	created_at 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at 		TIMESTAMP NULL DEFAULT NULL,
	deleted_at 		TIMESTAMP NULL DEFAULT NULL,
	created_by		VARCHAR(191) DEFAULT NULL,
	updated_by		VARCHAR(191) DEFAULT NULL,
	deleted_by		VARCHAR(191) DEFAULT NULL
);

CREATE TABLE wishlist (
	id				INT PRIMARY KEY AUTO_INCREMENT,
	tipe_user_id 	INT NOT NULL,
	lk_id			INT NULL,
	ident			VARCHAR(9) NOT NULL,
	content			TEXT,

	status 			TINYINT(1) DEFAULT 1,
	created_at 		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at 		TIMESTAMP NULL DEFAULT NULL,
	deleted_at 		TIMESTAMP NULL DEFAULT NULL,
	created_by		VARCHAR(191) DEFAULT NULL,
	updated_by		VARCHAR(191) DEFAULT NULL,
	deleted_by		VARCHAR(191) DEFAULT NULL,

	CONSTRAINT fk_wishlist_tipe_user 
		FOREIGN KEY (tipe_user_id) REFERENCES tipe_user(id),
	CONSTRAINT fk_wishlist_lk 
		FOREIGN KEY (lk_id) REFERENCES lk(id)
);